# Generated by Django 4.2 on 2023-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=10000)),
            ],
        ),
    ]
