# Generated by Django 4.2.1 on 2023-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='userName',
            field=models.CharField(default='korada', max_length=100),
        ),
    ]
